# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{typus_fluxiom}
  s.version = "2.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["T Koenig"]
  s.date = %q{2011-04-22}
  s.description = %q{typus loves fluxiom}
  s.email = %q{t.koenig@wollzelle.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    "app/controllers/fluxiom_controller.rb",
    "app/models/fluxiom_asset.rb",
    "app/models/fluxiom_resource.rb",
    "app/models/fluxiom_tag.rb",
    "app/models/fluxiom_user.rb",
    "app/views/admin/templates/_fluxiom_gallery.html.erb",
    "app/views/admin/templates/_fluxiom_gallery_item.erb",
    "app/views/admin/templates/_fluxiom_gallery_item_template.erb",
    "app/views/fluxiom/index.html.erb",
    "config/routes.rb",
    "lib/fluxiom/configuration.rb",
    "lib/fluxiom/engine.rb",
    "lib/fluxiom/helpers.rb",
    "lib/typus_fluxiom.rb",
    "public/vendor/typus/fluxiom/chooser.css",
    "public/vendor/typus/fluxiom/chooser.js",
    "public/vendor/typus/fluxiom/gallery.css",
    "public/vendor/typus/fluxiom/gallery.js",
    "public/vendor/typus/fluxiom/jquery.tmpl.js"
  ]
  s.homepage = %q{http://wollzelle.com}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{fluxiom loves typus}
  s.test_files = [
    "test/helper.rb",
    "test/test_flux_assets.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

