# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{typus_fluxiom}
  s.version = "3.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Thomas Koenig}, %q{William Meleyal}, %q{I.C. Wiener}]
  s.date = %q{2011-08-18}
  s.description = %q{typus loves fluxiom}
  s.email = %q{team@wollzelle.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "TODO"
  ]
  s.files = [
    "app/controllers/fluxiom_controller.rb",
    "app/views/admin/templates/_fluxiom_gallery.html.erb",
    "app/views/admin/templates/_fluxiom_gallery_item.erb",
    "app/views/admin/templates/_fluxiom_gallery_item_template.erb",
    "app/views/fluxiom/index.html.erb",
    "config/routes.rb",
    "lib/fluxiom/configuration.rb",
    "lib/fluxiom/engine.rb",
    "lib/fluxiom/helpers.rb",
    "lib/typus_fluxiom.rb",
    "public/vendor/typus/fluxiom/chooser/asset.js",
    "public/vendor/typus/fluxiom/chooser/chooser.css",
    "public/vendor/typus/fluxiom/chooser/chooser.js",
    "public/vendor/typus/fluxiom/chooser/spinner.gif",
    "public/vendor/typus/fluxiom/chooser/tag.js",
    "public/vendor/typus/fluxiom/fluxiom.js",
    "public/vendor/typus/fluxiom/gallery/gallery.css",
    "public/vendor/typus/fluxiom/gallery/gallery.js",
    "public/vendor/typus/fluxiom/vendor/backbone.js",
    "public/vendor/typus/fluxiom/vendor/jquery.js",
    "public/vendor/typus/fluxiom/vendor/jquery.tmpl.js",
    "public/vendor/typus/fluxiom/vendor/jquery.ui.js",
    "public/vendor/typus/fluxiom/vendor/jquery.viewport.js",
    "public/vendor/typus/fluxiom/vendor/underscore.js"
  ]
  s.homepage = %q{http://wollzelle.com}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.7}
  s.summary = %q{fluxiom loves typus}
  s.test_files = [
    "test/helper.rb",
    "test/test_flux_assets.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

